### ISSUE TITLE
Markdown whitespace gets ignored in rendering

### ISSUE THREAD

**Issue by cindyallis** [Floatist/gatsby-floatist-site#3]
Our blog posts (newly published on our site here [floatist.com/blog](http://floatist.com/blog)) are being rendered with MDXRenderer, which is from Gatsby, but whitespaces and newlines from the markdown files are ignored somehow. 

It's pretty critical for our blogs to look good but @yergom I think this is an easy fix for you :)

Component that renders each blog page:
/gatsby-floatist-site/src/pages/blog/{mdx.slug}.js

Example of markdown file rendered in the page:
/gatsby-floatist-site/content/blog/hospitality-trends-2023/index.mdx

(Each folder in /content is a post)

**Comment by yergom** [comment]
It took a while, because I did not know how gatsby works. In the end, the problem was not related to mdx, but to the styles you had defined. The mdx plugin parses an mdx file, and converfts it to a tree of react components. A paragraph in mdx is converted into a ```<p>``` element, and you had defined a global style for all paragraphs to not have margin. I've fixed that, but the whole styling is a bit messy in my opinion. I've also changed the way author images are linked to blogposts, since it does not make sense to copy paste the same image over and over.
